#!/bin/sh
# lib/cmd_aws.sh -- render and (optionally) apply the S3-side configuration.
#
# The bucket settings are where most of the cost control lives. Uploading
# straight into the target storage class beats lifecycle transitions on every
# axis: no per-object transition charge, no mandatory 30-day wait in STANDARD
# first, and no second copy of the object during the move. So there are no
# transition rules here on purpose -- rclone sets x-amz-storage-class on PUT.

cmd_bootstrap_usage() {
	cat <<'EOF'
Usage: nasbak bootstrap [what]

  --script            Print a shell script of aws-cli commands (default).
  --cloudformation    Print the CloudFormation template.
  --lifecycle         Print just the lifecycle configuration JSON.
  --iam               Print just the IAM policy JSON.
  --bucket-policy     Print just the bucket policy JSON.
  --apply             Run the aws-cli commands now. Needs administrative AWS
                      credentials in the environment, and does not create the
                      IAM user (do that once, by hand).

Run this from a workstation with the aws CLI, not from the NAS: the NAS should
only ever hold the least-privilege key.
EOF
}

cmd_bootstrap() {
	_what=script
	while [ $# -gt 0 ]; do
		case "$1" in
		--script) _what=script; shift ;;
		--cloudformation | --cfn) _what=cfn; shift ;;
		--lifecycle) _what=lifecycle; shift ;;
		--iam) _what=iam; shift ;;
		--bucket-policy) _what=bucketpolicy; shift ;;
		--apply) _what=apply; shift ;;
		-h | --help) cmd_bootstrap_usage; return 0 ;;
		*) error "unknown option: $1"; cmd_bootstrap_usage; return 2 ;;
		esac
	done

	config_load
	[ -n "$S3_BUCKET" ] || die "S3_BUCKET is not set. Run 'nasbak init' first."

	case "$_what" in
	lifecycle) aws_render_lifecycle ;;
	iam) aws_render iam-policy.json.tmpl ;;
	bucketpolicy) aws_render bucket-policy.json.tmpl ;;
	cfn) cat "$NASBAK_HOME/aws/cloudformation.yaml" ;;
	script) aws_render_script ;;
	apply) aws_apply ;;
	esac
}

# Substitute @@PLACEHOLDERS@@ in a template from aws/.
aws_render() {
	_ar_tmpl="$NASBAK_HOME/aws/$1"
	[ -f "$_ar_tmpl" ] || die "missing template: $_ar_tmpl"
	_ar_keep=${KEEP_VERSIONS:-3}
	sed \
		-e "s|@@BUCKET@@|$S3_BUCKET|g" \
		-e "s|@@REGION@@|$S3_REGION|g" \
		-e "s|@@RETENTION_DAYS@@|$VERSION_RETENTION_DAYS|g" \
		-e "s|@@KEEP_VERSIONS@@|$_ar_keep|g" \
		"$_ar_tmpl"
}

aws_render_lifecycle() {
	_arl_keep=${KEEP_VERSIONS:-3}
	if [ "$_arl_keep" -le 0 ]; then
		# NewerNoncurrentVersions must be omitted, not zero.
		aws_render lifecycle.json.tmpl | sed '/"NewerNoncurrentVersions"/d' |
			sed 's/"NoncurrentDays": \([0-9]*\),$/"NoncurrentDays": \1/'
	else
		aws_render lifecycle.json.tmpl
	fi
}

aws_render_script() {
	_ars_min=$(class_min_days "$STORAGE_CLASS")
	cat <<EOF
#!/bin/sh
# Generated by nasbak bootstrap on $(date '+%Y-%m-%d').
# Run with administrative AWS credentials, from a workstation (not the NAS).
set -eu

BUCKET=$S3_BUCKET
REGION=$S3_REGION

# 1. Create the bucket. us-east-1 is the one region that rejects a
#    LocationConstraint, hence the special case.
if [ "\$REGION" = us-east-1 ]; then
  aws s3api create-bucket --bucket "\$BUCKET" --region "\$REGION"
else
  aws s3api create-bucket --bucket "\$BUCKET" --region "\$REGION" \\
    --create-bucket-configuration LocationConstraint="\$REGION"
fi

# 2. Block all public access before anything is uploaded.
aws s3api put-public-access-block --bucket "\$BUCKET" \\
  --public-access-block-configuration \\
  BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true

# 3. Default encryption. SSE-S3 (AES256) is free; SSE-KMS bills per request
#    and a backup makes a lot of requests.
aws s3api put-bucket-encryption --bucket "\$BUCKET" \\
  --server-side-encryption-configuration '{
    "Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"},"BucketKeyEnabled":true}]
  }'

# 4. Versioning. This is what gives you "one live copy plus an undo window"
#    instead of a fresh full copy every month.
aws s3api put-bucket-versioning --bucket "\$BUCKET" \\
  --versioning-configuration Status=Enabled

# 5. Lifecycle. Expires superseded versions after $VERSION_RETENTION_DAYS days,
#    clears orphaned multipart uploads, and sweeps expired delete markers.
#    Your STORAGE_CLASS is $STORAGE_CLASS, minimum billing duration ${_ars_min} days.
cat > /tmp/nasbak-lifecycle.json <<'LIFECYCLE'
$(aws_render_lifecycle)
LIFECYCLE
aws s3api put-bucket-lifecycle-configuration --bucket "\$BUCKET" \\
  --lifecycle-configuration file:///tmp/nasbak-lifecycle.json

# 6. Refuse plaintext transport.
cat > /tmp/nasbak-bucket-policy.json <<'BUCKETPOLICY'
$(aws_render bucket-policy.json.tmpl)
BUCKETPOLICY
aws s3api put-bucket-policy --bucket "\$BUCKET" \\
  --policy file:///tmp/nasbak-bucket-policy.json

# 7. A least-privilege user for the NAS. It can mirror (including deleting
#    current objects, which only writes delete markers) but it cannot purge
#    version history, so a compromised NAS cannot erase the backup.
cat > /tmp/nasbak-iam-policy.json <<'IAMPOLICY'
$(aws_render iam-policy.json.tmpl)
IAMPOLICY
aws iam create-user --user-name nasbak-\$BUCKET || true
aws iam put-user-policy --user-name nasbak-\$BUCKET \\
  --policy-name nasbak-s3-access --policy-document file:///tmp/nasbak-iam-policy.json
aws iam create-access-key --user-name nasbak-\$BUCKET

# 8. A budget alarm, so a misconfiguration shows up in your inbox rather than
#    on next month's card statement. Replace the email address first.
# aws budgets create-budget --account-id "\$(aws sts get-caller-identity --query Account --output text)" \\
#   --budget '{"BudgetName":"nasbak-s3","BudgetLimit":{"Amount":"10","Unit":"USD"},"TimeUnit":"MONTHLY","BudgetType":"COST","CostFilters":{"Service":["Amazon Simple Storage Service"]}}' \\
#   --notifications-with-subscribers '[{"Notification":{"NotificationType":"ACTUAL","ComparisonOperator":"GREATER_THAN","Threshold":80,"ThresholdType":"PERCENTAGE"},"Subscribers":[{"SubscriptionType":"EMAIL","Address":"you@example.com"}]}]'

rm -f /tmp/nasbak-lifecycle.json /tmp/nasbak-bucket-policy.json /tmp/nasbak-iam-policy.json
echo "Done. Put the AccessKeyId and SecretAccessKey from step 7 into"
echo "$CONFIG_DIR/credentials on the NAS, then run: nasbak check"
EOF
}

aws_apply() {
	have aws || die "the aws CLI is not installed. Use 'nasbak bootstrap --script' instead."
	_lc="${TMPDIR:-/tmp}/nasbak-lifecycle.$$.json"
	_bp="${TMPDIR:-/tmp}/nasbak-bucket-policy.$$.json"
	# shellcheck disable=SC2064
	trap "rm -f '$_lc' '$_bp'" EXIT

	info "bucket $S3_BUCKET in $S3_REGION"

	if aws s3api head-bucket --bucket "$S3_BUCKET" >/dev/null 2>&1; then
		info "bucket already exists; updating its configuration"
	else
		info "creating bucket"
		if [ "$S3_REGION" = us-east-1 ]; then
			aws s3api create-bucket --bucket "$S3_BUCKET" --region "$S3_REGION" >/dev/null ||
				die "create-bucket failed"
		else
			aws s3api create-bucket --bucket "$S3_BUCKET" --region "$S3_REGION" \
				--create-bucket-configuration "LocationConstraint=$S3_REGION" >/dev/null ||
				die "create-bucket failed"
		fi
	fi

	info "blocking public access"
	aws s3api put-public-access-block --bucket "$S3_BUCKET" \
		--public-access-block-configuration \
		BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true ||
		die "put-public-access-block failed"

	info "enabling default SSE-S3 encryption"
	aws s3api put-bucket-encryption --bucket "$S3_BUCKET" \
		--server-side-encryption-configuration \
		'{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"},"BucketKeyEnabled":true}]}' ||
		die "put-bucket-encryption failed"

	info "enabling versioning"
	aws s3api put-bucket-versioning --bucket "$S3_BUCKET" \
		--versioning-configuration Status=Enabled || die "put-bucket-versioning failed"

	info "applying lifecycle rules (superseded versions expire after $VERSION_RETENTION_DAYS days)"
	aws_render_lifecycle >"$_lc"
	aws s3api put-bucket-lifecycle-configuration --bucket "$S3_BUCKET" \
		--lifecycle-configuration "file://$_lc" || die "put-bucket-lifecycle-configuration failed"

	info "requiring TLS"
	aws_render bucket-policy.json.tmpl >"$_bp"
	aws s3api put-bucket-policy --bucket "$S3_BUCKET" --policy "file://$_bp" ||
		die "put-bucket-policy failed"

	rm -f "$_lc" "$_bp"
	trap - EXIT
	ok "bucket configured"
	info "still to do by hand: create the IAM user and key ('nasbak bootstrap --iam' prints the policy)"
}
